#!/usr/bin/env php
<?php

declare(strict_types=1);

use PolarisDemo\Env;
use Yiisoft\Yii\Runner\Console\ConsoleApplicationRunner;

require __DIR__ . '/vendor/autoload.php';

Env::load(__DIR__);

(new ConsoleApplicationRunner(rootPath: __DIR__, debug: true))->run();
