services:
    _defaults:
        autowire: true
        autoconfigure: true

    PolarisDemo\Controller\:
        resource: '../src/Controller/'

    PolarisDemo\FileMailer:
        arguments: ['%kernel.project_dir%/var/mail.log']
