/* Generated by scripts/generate-namespaces.mjs from openapi.json; do not edit. */
import type { Client } from "openapi-fetch";
import type { paths } from "./schema.js";
import type { Init } from "./namespace.js";

/** The `admin` plugin's routes as methods of `client.admin`. */
export function admin(client: Client<paths>) {
    return {
        /** POST /admin/users/{id}/ban: Ban a user */
        banUser: (...init: Init<"/admin/users/{id}/ban", "post">) => client.POST("/admin/users/{id}/ban", ...init),
        /** POST /admin/organizations/{id}/drains: Create an audit drain */
        createDrain: (...init: Init<"/admin/organizations/{id}/drains", "post">) => client.POST("/admin/organizations/{id}/drains", ...init),
        /** POST /admin/grants: Grant an admin role */
        createGrant: (...init: Init<"/admin/grants", "post">) => client.POST("/admin/grants", ...init),
        /** POST /admin/keys: Create an API key */
        createKey: (...init: Init<"/admin/keys", "post">) => client.POST("/admin/keys", ...init),
        /** DELETE /admin/organizations/{id}/drains/{drainId}: Delete an audit drain */
        deleteDrain: (...init: Init<"/admin/organizations/{id}/drains/{drainId}", "delete">) => client.DELETE("/admin/organizations/{id}/drains/{drainId}", ...init),
        /** DELETE /admin/grants/{id}: Revoke an admin grant */
        deleteGrant: (...init: Init<"/admin/grants/{id}", "delete">) => client.DELETE("/admin/grants/{id}", ...init),
        /** DELETE /admin/keys/{id}: Delete an API key */
        deleteKey: (...init: Init<"/admin/keys/{id}", "delete">) => client.DELETE("/admin/keys/{id}", ...init),
        /** DELETE /admin/organizations/{id}: Delete an organization */
        deleteOrganization: (...init: Init<"/admin/organizations/{id}", "delete">) => client.DELETE("/admin/organizations/{id}", ...init),
        /** DELETE /admin/users/{id}: Delete a user */
        deleteUser: (...init: Init<"/admin/users/{id}", "delete">) => client.DELETE("/admin/users/{id}", ...init),
        /** POST /admin/users/{id}/impersonate: Impersonate a user */
        impersonateUser: (...init: Init<"/admin/users/{id}/impersonate", "post">) => client.POST("/admin/users/{id}/impersonate", ...init),
        /** GET /admin/organizations/{id}/drains: List an organization's audit drains */
        listDrains: (...init: Init<"/admin/organizations/{id}/drains", "get">) => client.GET("/admin/organizations/{id}/drains", ...init),
        /** GET /admin/users/{id}/mfa: List a user's MFA factors */
        listFactors: (...init: Init<"/admin/users/{id}/mfa", "get">) => client.GET("/admin/users/{id}/mfa", ...init),
        /** GET /admin/grants: List the admin grants */
        listGrants: (...init: Init<"/admin/grants", "get">) => client.GET("/admin/grants", ...init),
        /** GET /admin/keys: List the API keys */
        listKeys: (...init: Init<"/admin/keys", "get">) => client.GET("/admin/keys", ...init),
        /** GET /admin/organizations: List the organizations */
        listOrganizations: (...init: Init<"/admin/organizations", "get">) => client.GET("/admin/organizations", ...init),
        /** GET /admin/users/{id}/sessions: List a user's sessions */
        listSessions: (...init: Init<"/admin/users/{id}/sessions", "get">) => client.GET("/admin/users/{id}/sessions", ...init),
        /** GET /admin/users: List the users */
        listUsers: (...init: Init<"/admin/users", "get">) => client.GET("/admin/users", ...init),
        /** GET /admin/audit: Query the audit trail */
        queryAudit: (...init: Init<"/admin/audit", "get">) => client.GET("/admin/audit", ...init),
        /** GET /admin/organizations/{id}: Read an organization */
        readOrganization: (...init: Init<"/admin/organizations/{id}", "get">) => client.GET("/admin/organizations/{id}", ...init),
        /** GET /admin/users/{id}: Read a user */
        readUser: (...init: Init<"/admin/users/{id}", "get">) => client.GET("/admin/users/{id}", ...init),
        /** DELETE /admin/users/{id}/mfa/{factorId}: Remove an MFA factor */
        removeFactor: (...init: Init<"/admin/users/{id}/mfa/{factorId}", "delete">) => client.DELETE("/admin/users/{id}/mfa/{factorId}", ...init),
        /** DELETE /admin/users/{id}/mfa: Reset a user's MFA */
        resetMfa: (...init: Init<"/admin/users/{id}/mfa", "delete">) => client.DELETE("/admin/users/{id}/mfa", ...init),
        /** DELETE /admin/users/{id}/sessions: Revoke every session */
        revokeAllSessions: (...init: Init<"/admin/users/{id}/sessions", "delete">) => client.DELETE("/admin/users/{id}/sessions", ...init),
        /** DELETE /admin/users/{id}/sessions/{sessionId}: Revoke a session */
        revokeSession: (...init: Init<"/admin/users/{id}/sessions/{sessionId}", "delete">) => client.DELETE("/admin/users/{id}/sessions/{sessionId}", ...init),
        /** POST /admin/users/{id}/password: Set a user's password */
        setPassword: (...init: Init<"/admin/users/{id}/password", "post">) => client.POST("/admin/users/{id}/password", ...init),
        /** GET /admin/stats: Read the instance statistics */
        stats: (...init: Init<"/admin/stats", "get">) => client.GET("/admin/stats", ...init),
        /** POST /admin/organizations/{id}/drains/{drainId}/test: Test an audit drain */
        testDrain: (...init: Init<"/admin/organizations/{id}/drains/{drainId}/test", "post">) => client.POST("/admin/organizations/{id}/drains/{drainId}/test", ...init),
        /** POST /admin/users/{id}/unban: Unban a user */
        unbanUser: (...init: Init<"/admin/users/{id}/unban", "post">) => client.POST("/admin/users/{id}/unban", ...init),
        /** PATCH /admin/organizations/{id}/members/{userId}/roles: Set a member's roles */
        updateMemberRoles: (...init: Init<"/admin/organizations/{id}/members/{userId}/roles", "patch">) => client.PATCH("/admin/organizations/{id}/members/{userId}/roles", ...init),
    };
}

export type AdminApi = ReturnType<typeof admin>;
