/* Generated by scripts/generate-namespaces.mjs from openapi.json; do not edit. */
import type { Client } from "openapi-fetch";
import type { paths } from "./schema.js";
import type { Init } from "./namespace.js";

/** The `anonymous` plugin's routes as methods of `client.anonymous`. */
export function anonymous(client: Client<paths>) {
    return {
        /** POST /anonymous/convert: Convert the guest into an account */
        convert: (...init: Init<"/anonymous/convert", "post">) => client.POST("/anonymous/convert", ...init),
        /** POST /anonymous/sign-in: Sign in as a guest */
        signIn: (...init: Init<"/anonymous/sign-in", "post">) => client.POST("/anonymous/sign-in", ...init),
    };
}

export type AnonymousApi = ReturnType<typeof anonymous>;
