/* Generated by scripts/generate-namespaces.mjs from openapi.json; do not edit. */
import type { Client } from "openapi-fetch";
import type { paths } from "./schema.js";
import type { Init } from "./namespace.js";

/** The `api-keys` plugin's routes as methods of `client.apiKeys`. */
export function apiKeys(client: Client<paths>) {
    return {
        /** POST /api-keys: Create an API key */
        create: (...init: Init<"/api-keys", "post">) => client.POST("/api-keys", ...init),
        /** DELETE /api-keys/{id}: Revoke an API key */
        delete: (...init: Init<"/api-keys/{id}", "delete">) => client.DELETE("/api-keys/{id}", ...init),
        /** GET /api-keys: List API keys */
        list: (...init: Init<"/api-keys", "get">) => client.GET("/api-keys", ...init),
        /** GET /api-keys/{id}: Read an API key */
        read: (...init: Init<"/api-keys/{id}", "get">) => client.GET("/api-keys/{id}", ...init),
        /** POST /api-keys/{id}/rotate: Rotate an API key */
        rotate: (...init: Init<"/api-keys/{id}/rotate", "post">) => client.POST("/api-keys/{id}/rotate", ...init),
        /** PATCH /api-keys/{id}: Update an API key */
        update: (...init: Init<"/api-keys/{id}", "patch">) => client.PATCH("/api-keys/{id}", ...init),
        /** POST /api-keys/verify: Verify an API key */
        verify: (...init: Init<"/api-keys/verify", "post">) => client.POST("/api-keys/verify", ...init),
    };
}

export type ApiKeysApi = ReturnType<typeof apiKeys>;
