/* Generated by scripts/generate-namespaces.mjs from openapi.json; do not edit. */
import type { Client } from "openapi-fetch";
import type { paths } from "./schema.js";
import type { Init } from "./namespace.js";

/** The `audit` plugin's routes as methods of `client.audit`. */
export function audit(client: Client<paths>) {
    return {
        /** GET /audit/me: List the audit events where the caller is the actor or the subject */
        me: (...init: Init<"/audit/me", "get">) => client.GET("/audit/me", ...init),
        /** GET /audit/organization/{id}: List an organization's audit events */
        organization: (...init: Init<"/audit/organization/{id}", "get">) => client.GET("/audit/organization/{id}", ...init),
        /** GET /audit/types: List the audit event names and their descriptions */
        types: (...init: Init<"/audit/types", "get">) => client.GET("/audit/types", ...init),
    };
}

export type AuditApi = ReturnType<typeof audit>;
