/* Generated by scripts/generate-namespaces.mjs from openapi.json; do not edit. */
import type { Client } from "openapi-fetch";
import type { paths } from "./schema.js";
import type { Init } from "./namespace.js";

/** The `multi-session` plugin's routes as methods of `client.multiSession`. */
export function multiSession(client: Client<paths>) {
    return {
        /** GET /multi-session/last-method: Read the device's last sign-in method */
        lastMethod: (...init: Init<"/multi-session/last-method", "get">) => client.GET("/multi-session/last-method", ...init),
        /** GET /multi-session/list: List the accounts signed in on this device */
        list: (...init: Init<"/multi-session/list", "get">) => client.GET("/multi-session/list", ...init),
        /** DELETE /multi-session/{sessionId}: Sign one account out of this device */
        revoke: (...init: Init<"/multi-session/{sessionId}", "delete">) => client.DELETE("/multi-session/{sessionId}", ...init),
        /** POST /multi-session/switch: Switch to another account signed in on this device */
        switch: (...init: Init<"/multi-session/switch", "post">) => client.POST("/multi-session/switch", ...init),
    };
}

export type MultiSessionApi = ReturnType<typeof multiSession>;
