/* Generated by scripts/generate-namespaces.mjs from openapi.json; do not edit. */
import type { Client } from "openapi-fetch";
import type { paths } from "./schema.js";
import type { Init } from "./namespace.js";

/** The `oauth` plugin's routes as methods of `client.oauth`. */
export function oauth(client: Client<paths>) {
    return {
        /** POST /admin/oauth/clients: Register an OAuth client as an operator */
        adminCreateClient: (...init: Init<"/admin/oauth/clients", "post">) => client.POST("/admin/oauth/clients", ...init),
        /** DELETE /admin/oauth/clients/{id}: Delete an OAuth client as an operator */
        adminDeleteClient: (...init: Init<"/admin/oauth/clients/{id}", "delete">) => client.DELETE("/admin/oauth/clients/{id}", ...init),
        /** GET /admin/oauth/clients: List every OAuth client */
        adminListClients: (...init: Init<"/admin/oauth/clients", "get">) => client.GET("/admin/oauth/clients", ...init),
        /** GET /.well-known/oauth-authorization-server: Authorization server metadata */
        authorizationServer: (...init: Init<"/.well-known/oauth-authorization-server", "get">) => client.GET("/.well-known/oauth-authorization-server", ...init),
        /** GET /oauth2/authorize: Start an authorization (consent) request */
        authorize: (...init: Init<"/oauth2/authorize", "get">) => client.GET("/oauth2/authorize", ...init),
        /** POST /oauth2/ciba: Backchannel authentication request */
        ciba: (...init: Init<"/oauth2/ciba", "post">) => client.POST("/oauth2/ciba", ...init),
        /** POST /oauth2/ciba/{id}/decide: Approve or refuse a backchannel request */
        cibaDecide: (...init: Init<"/oauth2/ciba/{id}/decide", "post">) => client.POST("/oauth2/ciba/{id}/decide", ...init),
        /** GET /oauth2/ciba/pending: List pending backchannel requests */
        cibaPending: (...init: Init<"/oauth2/ciba/pending", "get">) => client.GET("/oauth2/ciba/pending", ...init),
        /** DELETE /oauth2/consents/{clientId}: Revoke a consent */
        consentRevoke: (...init: Init<"/oauth2/consents/{clientId}", "delete">) => client.DELETE("/oauth2/consents/{clientId}", ...init),
        /** GET /oauth2/consents: List your consents */
        consentsList: (...init: Init<"/oauth2/consents", "get">) => client.GET("/oauth2/consents", ...init),
        /** POST /orgs/{id}/oauth/clients: Register an OAuth client for the organization */
        createClient: (...init: Init<"/orgs/{id}/oauth/clients", "post">) => client.POST("/orgs/{id}/oauth/clients", ...init),
        /** POST /oauth2/authorize/decision: Approve or refuse an authorization request */
        decision: (...init: Init<"/oauth2/authorize/decision", "post">) => client.POST("/oauth2/authorize/decision", ...init),
        /** DELETE /orgs/{id}/oauth/clients/{clientId}: Delete an OAuth client of the organization */
        deleteClient: (...init: Init<"/orgs/{id}/oauth/clients/{clientId}", "delete">) => client.DELETE("/orgs/{id}/oauth/clients/{clientId}", ...init),
        /** POST /oauth2/device/approve: Approve or refuse a device */
        deviceApprove: (...init: Init<"/oauth2/device/approve", "post">) => client.POST("/oauth2/device/approve", ...init),
        /** POST /oauth2/device/code: Start the device flow */
        deviceCode: (...init: Init<"/oauth2/device/code", "post">) => client.POST("/oauth2/device/code", ...init),
        /** GET /oauth2/device/verify: Read the device behind a user code */
        deviceVerify: (...init: Init<"/oauth2/device/verify", "get">) => client.GET("/oauth2/device/verify", ...init),
        /** POST /oauth2/introspect: Introspect a token */
        introspect: (...init: Init<"/oauth2/introspect", "post">) => client.POST("/oauth2/introspect", ...init),
        /** GET /orgs/{id}/oauth/clients: List the organization's OAuth clients */
        listClients: (...init: Init<"/orgs/{id}/oauth/clients", "get">) => client.GET("/orgs/{id}/oauth/clients", ...init),
        /** GET /.well-known/openid-configuration: OpenID Connect Discovery */
        openIdConfiguration: (...init: Init<"/.well-known/openid-configuration", "get">) => client.GET("/.well-known/openid-configuration", ...init),
        /** GET /orgs/{id}/oauth/clients/{clientId}: Read an OAuth client of the organization */
        readClient: (...init: Init<"/orgs/{id}/oauth/clients/{clientId}", "get">) => client.GET("/orgs/{id}/oauth/clients/{clientId}", ...init),
        /** POST /oauth2/register: Register a client (RFC 7591) */
        register: (...init: Init<"/oauth2/register", "post">) => client.POST("/oauth2/register", ...init),
        /** POST /oauth2/revoke: Revoke a token */
        revoke: (...init: Init<"/oauth2/revoke", "post">) => client.POST("/oauth2/revoke", ...init),
        /** POST /oauth2/token: Issue tokens */
        token: (...init: Init<"/oauth2/token", "post">) => client.POST("/oauth2/token", ...init),
        /** PATCH /orgs/{id}/oauth/clients/{clientId}: Update an OAuth client of the organization */
        updateClient: (...init: Init<"/orgs/{id}/oauth/clients/{clientId}", "patch">) => client.PATCH("/orgs/{id}/oauth/clients/{clientId}", ...init),
        /** GET /oauth2/userinfo: The user's OpenID claims */
        userinfo: (...init: Init<"/oauth2/userinfo", "get">) => client.GET("/oauth2/userinfo", ...init),
        /** POST /oauth2/userinfo: The user's OpenID claims (POST) */
        userinfoPost: (...init: Init<"/oauth2/userinfo", "post">) => client.POST("/oauth2/userinfo", ...init),
    };
}

export type OauthApi = ReturnType<typeof oauth>;
