/* Generated by scripts/generate-namespaces.mjs from openapi.json; do not edit. */
import type { Client } from "openapi-fetch";
import type { paths } from "./schema.js";
import type { Init } from "./namespace.js";

/** The `passkey` plugin's routes as methods of `client.passkey`. */
export function passkey(client: Client<paths>) {
    return {
        /** POST /passkey/authenticate/options: Start a passkey sign-in */
        authenticateOptions: (...init: Init<"/passkey/authenticate/options", "post">) => client.POST("/passkey/authenticate/options", ...init),
        /** POST /passkey/authenticate/verify: Sign in with a passkey */
        authenticateVerify: (...init: Init<"/passkey/authenticate/verify", "post">) => client.POST("/passkey/authenticate/verify", ...init),
        /** DELETE /passkey/{id}: Remove a passkey */
        delete: (...init: Init<"/passkey/{id}", "delete">) => client.DELETE("/passkey/{id}", ...init),
        /** GET /passkey/list: List your passkeys */
        list: (...init: Init<"/passkey/list", "get">) => client.GET("/passkey/list", ...init),
        /** POST /passkey/register/options: Start registering a passkey */
        registerOptions: (...init: Init<"/passkey/register/options", "post">) => client.POST("/passkey/register/options", ...init),
        /** POST /passkey/register/verify: Finish registering a passkey */
        registerVerify: (...init: Init<"/passkey/register/verify", "post">) => client.POST("/passkey/register/verify", ...init),
        /** PATCH /passkey/{id}: Rename a passkey */
        rename: (...init: Init<"/passkey/{id}", "patch">) => client.PATCH("/passkey/{id}", ...init),
    };
}

export type PasskeyApi = ReturnType<typeof passkey>;
