/* Generated by scripts/generate-namespaces.mjs from openapi.json; do not edit. */
import type { Client } from "openapi-fetch";
import type { paths } from "./schema.js";
import type { Init } from "./namespace.js";

/** The `passwordless` plugin's routes as methods of `client.passwordless`. */
export function passwordless(client: Client<paths>) {
    return {
        /** POST /email-otp/reset-password: Reset the password with an email code */
        emailOtpResetPassword: (...init: Init<"/email-otp/reset-password", "post">) => client.POST("/email-otp/reset-password", ...init),
        /** POST /email-otp/send: Send an email code */
        emailOtpSend: (...init: Init<"/email-otp/send", "post">) => client.POST("/email-otp/send", ...init),
        /** POST /email-otp/verify: Sign in with an email code */
        emailOtpVerify: (...init: Init<"/email-otp/verify", "post">) => client.POST("/email-otp/verify", ...init),
        /** POST /email-otp/verify-email: Verify the email with a code */
        emailOtpVerifyEmail: (...init: Init<"/email-otp/verify-email", "post">) => client.POST("/email-otp/verify-email", ...init),
        /** POST /magic-link/exchange: Exchange the magic link's code for the session */
        magicLinkExchange: (...init: Init<"/magic-link/exchange", "post">) => client.POST("/magic-link/exchange", ...init),
        /** POST /magic-link/send: Send a magic link */
        magicLinkSend: (...init: Init<"/magic-link/send", "post">) => client.POST("/magic-link/send", ...init),
        /** GET /magic-link/verify: Open a magic link */
        magicLinkVerify: (...init: Init<"/magic-link/verify", "get">) => client.GET("/magic-link/verify", ...init),
        /** POST /one-time-token/generate: Generate a one-time token */
        oneTimeTokenGenerate: (...init: Init<"/one-time-token/generate", "post">) => client.POST("/one-time-token/generate", ...init),
        /** POST /one-time-token/verify: Sign in with a one-time token */
        oneTimeTokenVerify: (...init: Init<"/one-time-token/verify", "post">) => client.POST("/one-time-token/verify", ...init),
        /** POST /phone/add: Add a phone number */
        phoneAdd: (...init: Init<"/phone/add", "post">) => client.POST("/phone/add", ...init),
        /** POST /phone/confirm: Confirm a phone number */
        phoneConfirm: (...init: Init<"/phone/confirm", "post">) => client.POST("/phone/confirm", ...init),
        /** POST /phone/send: Send a phone sign-in code */
        phoneSend: (...init: Init<"/phone/send", "post">) => client.POST("/phone/send", ...init),
        /** POST /phone/verify: Sign in with a phone code */
        phoneVerify: (...init: Init<"/phone/verify", "post">) => client.POST("/phone/verify", ...init),
    };
}

export type PasswordlessApi = ReturnType<typeof passwordless>;
