/* Generated by scripts/generate-namespaces.mjs from openapi.json; do not edit. */
import type { Client } from "openapi-fetch";
import type { paths } from "./schema.js";
import type { Init } from "./namespace.js";

/** The `scim` plugin's routes as methods of `client.scim`. */
export function scim(client: Client<paths>) {
    return {
        /** DELETE /admin/scim/connections/{id}: Remove a SCIM connection (operator) */
        adminDeleteConnection: (...init: Init<"/admin/scim/connections/{id}", "delete">) => client.DELETE("/admin/scim/connections/{id}", ...init),
        /** GET /admin/scim/connections: List the SCIM connections of every organization */
        adminListConnections: (...init: Init<"/admin/scim/connections", "get">) => client.GET("/admin/scim/connections", ...init),
        /** POST /orgs/{id}/scim/connections: Create a SCIM connection */
        createConnection: (...init: Init<"/orgs/{id}/scim/connections", "post">) => client.POST("/orgs/{id}/scim/connections", ...init),
        /** POST /scim/v2/{connectionId}/Groups: Create a SCIM group */
        createGroup: (...init: Init<"/scim/v2/{connectionId}/Groups", "post">) => client.POST("/scim/v2/{connectionId}/Groups", ...init),
        /** POST /scim/v2/{connectionId}/Users: Create a SCIM user */
        createUser: (...init: Init<"/scim/v2/{connectionId}/Users", "post">) => client.POST("/scim/v2/{connectionId}/Users", ...init),
        /** DELETE /orgs/{id}/scim/connections/{connectionId}: Decommission a SCIM connection */
        decommissionConnection: (...init: Init<"/orgs/{id}/scim/connections/{connectionId}", "delete">) => client.DELETE("/orgs/{id}/scim/connections/{connectionId}", ...init),
        /** DELETE /scim/v2/{connectionId}/Groups/{id}: Delete a SCIM group */
        deleteGroup: (...init: Init<"/scim/v2/{connectionId}/Groups/{id}", "delete">) => client.DELETE("/scim/v2/{connectionId}/Groups/{id}", ...init),
        /** DELETE /scim/v2/{connectionId}/Users/{id}: Delete a SCIM user */
        deleteUser: (...init: Init<"/scim/v2/{connectionId}/Users/{id}", "delete">) => client.DELETE("/scim/v2/{connectionId}/Users/{id}", ...init),
        /** GET /orgs/{id}/scim/connections: List the organization's SCIM connections */
        listConnections: (...init: Init<"/orgs/{id}/scim/connections", "get">) => client.GET("/orgs/{id}/scim/connections", ...init),
        /** GET /scim/v2/{connectionId}/Groups: List SCIM groups */
        listGroups: (...init: Init<"/scim/v2/{connectionId}/Groups", "get">) => client.GET("/scim/v2/{connectionId}/Groups", ...init),
        /** GET /scim/v2/{connectionId}/Users: List SCIM users */
        listUsers: (...init: Init<"/scim/v2/{connectionId}/Users", "get">) => client.GET("/scim/v2/{connectionId}/Users", ...init),
        /** PATCH /scim/v2/{connectionId}/Groups/{id}: Patch a SCIM group */
        patchGroup: (...init: Init<"/scim/v2/{connectionId}/Groups/{id}", "patch">) => client.PATCH("/scim/v2/{connectionId}/Groups/{id}", ...init),
        /** PATCH /scim/v2/{connectionId}/Users/{id}: Patch a SCIM user */
        patchUser: (...init: Init<"/scim/v2/{connectionId}/Users/{id}", "patch">) => client.PATCH("/scim/v2/{connectionId}/Users/{id}", ...init),
        /** GET /orgs/{id}/scim/connections/{connectionId}: Read a SCIM connection */
        readConnection: (...init: Init<"/orgs/{id}/scim/connections/{connectionId}", "get">) => client.GET("/orgs/{id}/scim/connections/{connectionId}", ...init),
        /** GET /scim/v2/{connectionId}/Groups/{id}: Read a SCIM group */
        readGroup: (...init: Init<"/scim/v2/{connectionId}/Groups/{id}", "get">) => client.GET("/scim/v2/{connectionId}/Groups/{id}", ...init),
        /** GET /scim/v2/{connectionId}/Users/{id}: Read a SCIM user */
        readUser: (...init: Init<"/scim/v2/{connectionId}/Users/{id}", "get">) => client.GET("/scim/v2/{connectionId}/Users/{id}", ...init),
        /** PUT /scim/v2/{connectionId}/Groups/{id}: Replace a SCIM group */
        replaceGroup: (...init: Init<"/scim/v2/{connectionId}/Groups/{id}", "put">) => client.PUT("/scim/v2/{connectionId}/Groups/{id}", ...init),
        /** PUT /scim/v2/{connectionId}/Users/{id}: Replace a SCIM user */
        replaceUser: (...init: Init<"/scim/v2/{connectionId}/Users/{id}", "put">) => client.PUT("/scim/v2/{connectionId}/Users/{id}", ...init),
        /** GET /scim/v2/{connectionId}/ResourceTypes: SCIM resource types */
        resourceTypes: (...init: Init<"/scim/v2/{connectionId}/ResourceTypes", "get">) => client.GET("/scim/v2/{connectionId}/ResourceTypes", ...init),
        /** POST /orgs/{id}/scim/connections/{connectionId}/rotate: Rotate a SCIM connection token */
        rotateConnection: (...init: Init<"/orgs/{id}/scim/connections/{connectionId}/rotate", "post">) => client.POST("/orgs/{id}/scim/connections/{connectionId}/rotate", ...init),
        /** GET /scim/v2/{connectionId}/Schemas: SCIM schemas */
        schemas: (...init: Init<"/scim/v2/{connectionId}/Schemas", "get">) => client.GET("/scim/v2/{connectionId}/Schemas", ...init),
        /** GET /scim/v2/{connectionId}/ServiceProviderConfig: SCIM service provider configuration */
        serviceProviderConfig: (...init: Init<"/scim/v2/{connectionId}/ServiceProviderConfig", "get">) => client.GET("/scim/v2/{connectionId}/ServiceProviderConfig", ...init),
    };
}

export type ScimApi = ReturnType<typeof scim>;
