/* Generated by scripts/generate-namespaces.mjs from openapi.json; do not edit. */
import type { Client } from "openapi-fetch";
import type { paths } from "./schema.js";
import type { Init } from "./namespace.js";

/** The `sentinel` plugin's routes as methods of `client.sentinel`. */
export function sentinel(client: Client<paths>) {
    return {
        /** POST /admin/sentinel/ip-rules: Add an IP rule */
        createIpRule: (...init: Init<"/admin/sentinel/ip-rules", "post">) => client.POST("/admin/sentinel/ip-rules", ...init),
        /** DELETE /admin/sentinel/ip-rules/{id}: Remove an IP rule */
        deleteIpRule: (...init: Init<"/admin/sentinel/ip-rules/{id}", "delete">) => client.DELETE("/admin/sentinel/ip-rules/{id}", ...init),
        /** GET /admin/sentinel/decisions: List the sentinel's decisions */
        listDecisions: (...init: Init<"/admin/sentinel/decisions", "get">) => client.GET("/admin/sentinel/decisions", ...init),
        /** GET /admin/sentinel/ip-rules: List the IP rules */
        listIpRules: (...init: Init<"/admin/sentinel/ip-rules", "get">) => client.GET("/admin/sentinel/ip-rules", ...init),
        /** POST /admin/sentinel/unblock: Clear the counters of an identifier */
        unblock: (...init: Init<"/admin/sentinel/unblock", "post">) => client.POST("/admin/sentinel/unblock", ...init),
    };
}

export type SentinelApi = ReturnType<typeof sentinel>;
