/* Generated by scripts/generate-namespaces.mjs from openapi.json; do not edit. */
import type { Client } from "openapi-fetch";
import type { paths } from "./schema.js";
import type { Init } from "./namespace.js";

/** The `social` plugin's routes as methods of `client.social`. */
export function social(client: Client<paths>) {
    return {
        /** GET /social/accounts: List your linked provider accounts */
        accounts: (...init: Init<"/social/accounts", "get">) => client.GET("/social/accounts", ...init),
        /** GET /social/{provider}/callback: The provider's callback */
        callback: (...init: Init<"/social/{provider}/callback", "get">) => client.GET("/social/{provider}/callback", ...init),
        /** POST /social/{provider}/callback: The provider's callback (form_post) */
        callbackPost: (...init: Init<"/social/{provider}/callback", "post">) => client.POST("/social/{provider}/callback", ...init),
        /** POST /social/exchange: Exchange the sign-in code for the session */
        exchange: (...init: Init<"/social/exchange", "post">) => client.POST("/social/exchange", ...init),
        /** POST /social/{provider}/link: Link a provider to your account */
        link: (...init: Init<"/social/{provider}/link", "post">) => client.POST("/social/{provider}/link", ...init),
        /** POST /social/google/one-tap: Sign in with Google One Tap */
        oneTap: (...init: Init<"/social/google/one-tap", "post">) => client.POST("/social/google/one-tap", ...init),
        /** POST /social/{provider}/start: Start a social sign-in */
        start: (...init: Init<"/social/{provider}/start", "post">) => client.POST("/social/{provider}/start", ...init),
        /** POST /social/{provider}/token: Get a provider token for the user */
        token: (...init: Init<"/social/{provider}/token", "post">) => client.POST("/social/{provider}/token", ...init),
        /** DELETE /social/{provider}: Unlink a provider */
        unlink: (...init: Init<"/social/{provider}", "delete">) => client.DELETE("/social/{provider}", ...init),
    };
}

export type SocialApi = ReturnType<typeof social>;
