/* Generated by scripts/generate-namespaces.mjs from openapi.json; do not edit. */
import type { Client } from "openapi-fetch";
import type { paths } from "./schema.js";
import type { Init } from "./namespace.js";

/** The `sso` plugin's routes as methods of `client.sso`. */
export function sso(client: Client<paths>) {
    return {
        /** POST /orgs/{id}/sso/domains: Add an SSO domain */
        addDomain: (...init: Init<"/orgs/{id}/sso/domains", "post">) => client.POST("/orgs/{id}/sso/domains", ...init),
        /** DELETE /admin/sso/providers/{id}: Remove an SSO provider (operator) */
        adminDeleteProvider: (...init: Init<"/admin/sso/providers/{id}", "delete">) => client.DELETE("/admin/sso/providers/{id}", ...init),
        /** GET /admin/sso/providers: List the SSO providers of every organization */
        adminListProviders: (...init: Init<"/admin/sso/providers", "get">) => client.GET("/admin/sso/providers", ...init),
        /** POST /orgs/{id}/sso/providers: Add an SSO provider */
        createProvider: (...init: Init<"/orgs/{id}/sso/providers", "post">) => client.POST("/orgs/{id}/sso/providers", ...init),
        /** DELETE /orgs/{id}/sso/domains/{domainId}: Remove an SSO domain */
        deleteDomain: (...init: Init<"/orgs/{id}/sso/domains/{domainId}", "delete">) => client.DELETE("/orgs/{id}/sso/domains/{domainId}", ...init),
        /** DELETE /orgs/{id}/sso/providers/{providerId}: Remove an SSO provider */
        deleteProvider: (...init: Init<"/orgs/{id}/sso/providers/{providerId}", "delete">) => client.DELETE("/orgs/{id}/sso/providers/{providerId}", ...init),
        /** POST /sso/exchange: Exchange the sign-on code for the session */
        exchange: (...init: Init<"/sso/exchange", "post">) => client.POST("/sso/exchange", ...init),
        /** GET /orgs/{id}/sso/domains: List the organization's SSO domains */
        listDomains: (...init: Init<"/orgs/{id}/sso/domains", "get">) => client.GET("/orgs/{id}/sso/domains", ...init),
        /** GET /orgs/{id}/sso/providers: List the organization's SSO providers */
        listProviders: (...init: Init<"/orgs/{id}/sso/providers", "get">) => client.GET("/orgs/{id}/sso/providers", ...init),
        /** POST /sso/logout: Single logout from the application */
        logout: (...init: Init<"/sso/logout", "post">) => client.POST("/sso/logout", ...init),
        /** GET /sso/metadata/{providerId}: SAML service provider metadata */
        metadata: (...init: Init<"/sso/metadata/{providerId}", "get">) => client.GET("/sso/metadata/{providerId}", ...init),
        /** GET /sso/callback/{providerId}: OIDC callback */
        oidcCallback: (...init: Init<"/sso/callback/{providerId}", "get">) => client.GET("/sso/callback/{providerId}", ...init),
        /** GET /orgs/{id}/sso/providers/{providerId}: Read an SSO provider */
        readProvider: (...init: Init<"/orgs/{id}/sso/providers/{providerId}", "get">) => client.GET("/orgs/{id}/sso/providers/{providerId}", ...init),
        /** POST /sso/callback/{providerId}: SAML assertion consumer */
        samlCallback: (...init: Init<"/sso/callback/{providerId}", "post">) => client.POST("/sso/callback/{providerId}", ...init),
        /** POST /sso/sign-in: Start a single sign-on */
        signIn: (...init: Init<"/sso/sign-in", "post">) => client.POST("/sso/sign-in", ...init),
        /** POST /sso/slo/{providerId}: SAML single logout (POST binding) */
        sloPost: (...init: Init<"/sso/slo/{providerId}", "post">) => client.POST("/sso/slo/{providerId}", ...init),
        /** GET /sso/slo/{providerId}: SAML single logout (redirect binding) */
        sloRedirect: (...init: Init<"/sso/slo/{providerId}", "get">) => client.GET("/sso/slo/{providerId}", ...init),
        /** POST /orgs/{id}/sso/providers/{providerId}/test: Test an SSO provider's configuration */
        testProvider: (...init: Init<"/orgs/{id}/sso/providers/{providerId}/test", "post">) => client.POST("/orgs/{id}/sso/providers/{providerId}/test", ...init),
        /** PATCH /orgs/{id}/sso/providers/{providerId}: Update an SSO provider */
        updateProvider: (...init: Init<"/orgs/{id}/sso/providers/{providerId}", "patch">) => client.PATCH("/orgs/{id}/sso/providers/{providerId}", ...init),
        /** POST /orgs/{id}/sso/domains/{domainId}/verify: Verify an SSO domain */
        verifyDomain: (...init: Init<"/orgs/{id}/sso/domains/{domainId}/verify", "post">) => client.POST("/orgs/{id}/sso/domains/{domainId}/verify", ...init),
    };
}

export type SsoApi = ReturnType<typeof sso>;
