/* Generated by scripts/generate-namespaces.mjs from openapi.json; do not edit. */
import type { Client } from "openapi-fetch";
import type { paths } from "./schema.js";
import type { Init } from "./namespace.js";

/** The `username` plugin's routes as methods of `client.username`. */
export function username(client: Client<paths>) {
    return {
        /** POST /username/sign-in: Sign in with a username and a password */
        signIn: (...init: Init<"/username/sign-in", "post">) => client.POST("/username/sign-in", ...init),
        /** PATCH /username: Set or change your username */
        update: (...init: Init<"/username", "patch">) => client.PATCH("/username", ...init),
    };
}

export type UsernameApi = ReturnType<typeof username>;
